# Generated by Django 5.2.4 on 2025-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoMpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_celular', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('resposta_api', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
