# Generated by Django 5.2.4 on 2025-07-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaompesa',
            name='mensagem_erro',
            field=models.TextField(blank=True, help_text='Armazena a mensagem de erro, se houver.', null=True),
        ),
    ]
