# Generated by Django 5.2.4 on 2025-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0002_transacaompesa_mensagem_erro'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaompesa',
            name='tipo_transacao',
            field=models.CharField(choices=[('C2B', 'Entrada (C2B)'), ('B2C', 'Saída (B2C)')], default='C2B', max_length=3),
        ),
    ]
