# Generated by Django 5.2.4 on 2025-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
