# Generated by Django 5.2.4 on 2025-07-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('PRO', 'Pro'), ('TRIAL_EXPIRED', 'Trial Expired')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
