# Generated by Django 5.2.4 on 2025-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_saque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('package_type', models.CharField(choices=[('TRIAL', 'Trial'), ('ONE_TIME', 'One-Time Payment'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
            ],
        ),
    ]
