# Generated by Django 5.2.4 on 2025-07-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='saque',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
