# Generated by Django 5.2.4 on 2025-07-30 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saque_numero_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='withdrawal_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.package'),
        ),
    ]
