# Generated by Django 5.2.4 on 2025-07-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_package_withdrawal_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_withdrawal_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
