# Generated by Django 5.2.4 on 2025-07-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_custom_withdrawal_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saque',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
