# Generated by Django 5.2.4 on 2025-07-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_saque_valor_liquido'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='transaction_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_transaction_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
