# Generated by Django 5.2.4 on 2025-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactosuporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactosuporte',
            name='pinterest_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactosuporte',
            name='x_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
