# Generated by Django 5.2.4 on 2025-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactosuporte_pinterest_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
