# Generated by Django 5.2.4 on 2025-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_checkoutsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='https://paymoz.co.mz/api/v1', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração da API',
                'verbose_name_plural': 'Configurações da API',
            },
        ),
    ]
