# Generated by Django 5.2.4 on 2025-07-31 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_apisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkout_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_transactions', to='core.checkoutsession'),
        ),
    ]
