# Generated by Django 5.2.4 on 2025-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transaction_checkout_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saque',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10),
        ),
    ]
