# Generated by Django 5.2.4 on 2025-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_saque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='dados_cliente_custom',
            field=models.JSONField(blank=True, default=dict, help_text='Dados customizados preenchidos pelo cliente no checkout.'),
        ),
    ]
