# Generated by Django 5.2.4 on 2025-08-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_checkoutsession_dados_cliente_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
