# Generated by Django 5.2.4 on 2025-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transaction_payment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
