# Generated by Django 5.2.4 on 2025-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saque Administrativo',
                'verbose_name_plural': 'Saques Administrativos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminWithdrawalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentagem do lucro líquido disponível para saque administrativo.', max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuração de Saque Administrativo',
                'verbose_name_plural': 'Configurações de Saque Administrativo',
            },
        ),
    ]
