# Generated by Django 5.2.4 on 2025-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_adminwithdrawal_adminwithdrawalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwithdrawalsettings',
            name='total_withdrawn_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total já sacado do lucro líquido.', max_digits=10),
        ),
    ]
