# Generated by Django 5.2.4 on 2025-08-01 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_alter_saque_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável para a página do produto. Deixe em branco para gerar automaticamente.', max_length=255, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (MZN)')),
                ('vendidos', models.PositiveIntegerField(default=0, verbose_name='Quantidade Vendida')),
                ('depoimentos', models.JSONField(blank=True, default=list, help_text='Lista de depoimentos. Ex: [{"autor": "João", "texto": "Excelente!"}]', null=True)),
                ('gatilhos_mentais', models.JSONField(blank=True, default=dict, help_text='Gatilhos mentais. Ex: {"escassez": "Apenas 10 vagas!"}', null=True)),
                ('ativo', models.BooleanField(default=False, verbose_name='Página de Vendas Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.userprofile', verbose_name='Dono do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
