# Generated by Django 5.2.4 on 2025-08-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='produtos_imagens/', verbose_name='Imagem de Destaque'),
        ),
    ]
