# Generated by Django 5.2.4 on 2025-08-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_imagem_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ativo',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('CURSO_ONLINE', 'Curso Online'), ('EBOOK', 'E-book'), ('SOFTWARE', 'Software'), ('CONSULTORIA', 'Consultoria'), ('TEMPLATE', 'Template'), ('OUTRO', 'Outro')], default='CURSO_ONLINE', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='css_customizado',
            field=models.TextField(blank=True, verbose_name='CSS Personalizado'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(blank=True, help_text='Aparece nos cards e resumos.', verbose_name='Descrição Curta'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_seo',
            field=models.CharField(blank=True, help_text='Descrição para o Google (máx. 160 caracteres).', max_length=160, verbose_name='Descrição SEO'),
        ),
        migrations.AddField(
            model_name='produto',
            name='habilitar_analytics',
            field=models.BooleanField(default=True, verbose_name='Habilitar Analytics'),
        ),
        migrations.AddField(
            model_name='produto',
            name='mostrar_relacionados',
            field=models.BooleanField(default=True, verbose_name='Mostrar Produtos Relacionados'),
        ),
        migrations.AddField(
            model_name='produto',
            name='o_que_esta_incluido',
            field=models.JSONField(blank=True, default=list, help_text='Lista de itens incluídos no produto. Ex: ["50+ videoaulas", "Material de apoio"]'),
        ),
        migrations.AddField(
            model_name='produto',
            name='permitir_comentarios',
            field=models.BooleanField(default=False, verbose_name='Permitir Comentários na Página'),
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('RASCUNHO', 'Rascunho'), ('INATIVO', 'Inativo')], default='RASCUNHO', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='produto',
            name='titulo_seo',
            field=models.CharField(blank=True, help_text='Título que aparecerá no Google (máx. 60 caracteres).', max_length=60, verbose_name='Título SEO'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='depoimentos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de depoimentos. Ex: [{"autor": "João", "profissao": "Estudante", "texto": "Excelente!", "rating": 5}]'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='gatilhos_mentais',
            field=models.JSONField(blank=True, default=dict, help_text='Gatilhos mentais. Ex: {"escassez": {"texto": "Apenas 10 vagas!"}, "garantia": {"dias": 30}}'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável. Deixe em branco para gerar automaticamente.', max_length=255, unique=True),
        ),
    ]
