# Generated by Django 5.2.4 on 2025-08-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_ativo_produto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIncluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='itens_incluidos_arquivos/', verbose_name='Arquivo (Opcional)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_incluidos', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item Incluído',
                'verbose_name_plural': 'Itens Incluídos',
                'ordering': ['descricao'],
            },
        ),
    ]
