# Generated by Django 5.2.4 on 2025-08-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_itemincluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos_galeria/', verbose_name='Imagem da Galeria')),
                ('legenda', models.CharField(blank=True, max_length=255, verbose_name='Legenda (Opcional)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_galeria', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['ordem'],
            },
        ),
    ]
