# Generated by Django 5.2.4 on 2025-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produtoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='campos_personalizados',
            field=models.JSONField(blank=True, default=list, help_text='Definição de campos personalizados para o checkout. Ex: [{"label": "Seu WhatsApp", "tipo": "tel", "obrigatorio": true}]'),
        ),
    ]
