# Generated by Django 5.2.4 on 2025-08-02 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_campos_personalizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('nome_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Avaliação de Produto',
                'verbose_name_plural': 'Avaliações de Produtos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
