# Generated by Django 5.2.4 on 2025-08-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_avaliacaoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='mensagem_whatsapp_sucesso',
            field=models.TextField(blank=True, help_text='Mensagem personalizada enviada ao cliente após pagamento bem-sucedido. Use {nome_cliente}, {nome_produto}, {valor_pago} para variáveis.', null=True, verbose_name='Mensagem WhatsApp de Sucesso'),
        ),
    ]
