# Generated by Django 5.2.4 on 2025-08-03 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_produto_mensagem_whatsapp_sucesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaoproduto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemincluido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produtoimagem',
            options={},
        ),
        migrations.AddField(
            model_name='avaliacaoproduto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoproduto',
            unique_together={('produto', 'user')},
        ),
        migrations.RemoveField(
            model_name='itemincluido',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='produtoimagem',
            name='legenda',
        ),
        migrations.RemoveField(
            model_name='produtoimagem',
            name='ordem',
        ),
        migrations.AddField(
            model_name='produto',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL para onde o cliente será redirecionado após o pagamento bem-sucedido. Se deixado em branco, será usada uma página de sucesso padrão.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='itemincluido',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemincluido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_incluidos', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='mensagem_whatsapp_sucesso',
            field=models.TextField(blank=True, help_text='Mensagem personalizada para enviar ao comprador no WhatsApp após a compra. Use {nome_cliente}, {nome_produto}, {valor_pago}.', null=True),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(upload_to='produtos_galeria/'),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_galeria', to='produtos.produto'),
        ),
        migrations.RemoveField(
            model_name='avaliacaoproduto',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='avaliacaoproduto',
            name='celular_cliente',
        ),
        migrations.RemoveField(
            model_name='avaliacaoproduto',
            name='email_cliente',
        ),
        migrations.RemoveField(
            model_name='avaliacaoproduto',
            name='nome_cliente',
        ),
    ]