# Generated by Django 5.2.4 on 2025-08-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_avaliacaoproduto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='titulo_cabecalho',
            field=models.CharField(blank=True, help_text='Título que aparecerá no topo da página de vendas. Se deixado em branco, o nome do produto será usado.', max_length=100, verbose_name='Título do Cabeçalho'),
        ),
    ]
