# Generated by Django 5.2.4 on 2025-08-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_produto_titulo_cabecalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_criador',
            field=models.ImageField(blank=True, null=True, upload_to='criadores_fotos/', verbose_name='Foto do Criador'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sobre_o_criador',
            field=models.TextField(blank=True, help_text='Uma breve biografia que aparecerá na página de vendas para gerar confiança.', verbose_name='Sobre o Criador'),
        ),
        migrations.AddField(
            model_name='produto',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link do vídeo (YouTube, Vimeo). Aparecerá no topo da página. Use o link de incorporação (embed).', max_length=500, null=True, verbose_name='URL do Vídeo de Vendas'),
        ),
    ]
