# Generated by Django 5.2.4 on 2025-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_produto_foto_criador_produto_sobre_o_criador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='ID do seu Pixel do Facebook para rastreamento de conversões.', max_length=100, verbose_name='Facebook Pixel ID'),
        ),
    ]
