# Generated by Django 5.2.4 on 2025-08-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_produto_facebook_pixel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='Lista de Perguntas Frequentes (FAQ). Ex: [{"pergunta": "Como acesso?", "resposta": "Após a compra..."}]'),
        ),
    ]
