# Generated by Django 5.2.4 on 2025-08-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_produto_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='arquivo_download',
            field=models.FileField(blank=True, help_text='Ficheiro digital para download após a compra (ex: PDF, ZIP).', null=True, upload_to='produtos_downloads/'),
        ),
    ]
