# Generated by Django 5.2.4 on 2025-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_produto_arquivo_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Oferta (MZN)'),
        ),
    ]
