"""
Django settings for paymoz project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k95)5uo8w)@f)%*6jljp8!tb0&k+$(@^a3u3r4+0n-7k8i2)i8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'produtos',
    'tinymce', # Adicionado para o editor de texto rico
]

TINYMCE_DEFAULT_CONFIG = {
    'height': 300,
    'menubar': False,
    'plugins': 'advlist,autolink,lists,link,image,charmap,preview,anchor,'
               'searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,code,help,wordcount',
    'toolbar': 'undo redo | formatselect | '
               'bold italic backcolor | alignleft aligncenter '
               'alignright alignjustify | bullist numlist outdent indent | '
               'removeformat | help',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'paymoz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.support_contacts',
            ],
        },
    },
]

WSGI_APPLICATION = 'paymoz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'paymoz',
        'USER': 'neuratech',
        'PASSWORD': 'Cadeira33',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-pt'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# URL para arquivos estáticos (note a barra inicial)
STATIC_URL = '/static/'

# Pasta onde o collectstatic vai copiar todos os arquivos estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Pastas adicionais com arquivos estáticos (se tiver)
STATICFILES_DIRS = [
    BASE_DIR / 'core/static',
]

# Configurações para arquivos de mídia (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}

# --- Configurações de SSO ---
CLIENT_ID = 'WBLaGrnKqUBn7wNNUFmrykhC3gbnkJF1WZivRzLW'
CLIENT_SECRET = 'iD63EmTIUz48gxnnoMrWZGgndpIZDJMOrMtiVfBKKXsWumWdsDLTPyrRAKV89k9bFtpQgsGHLgOnSGGPhIW0qAfrG4Tm06CU3ZA6yxWew3I6mhdmc4fpYGzNzPPr2qX7'

# URIs de redirecionamento
SSO_REDIRECT_URI = 'https://4d663b22079f.ngrok-free.app/sso/callback/'
SSO_POST_LOGOUT_REDIRECT_URI = 'https://4d663b22079f.ngrok-free.app/logout-success/'

# Endpoints do provedor de SSO
SSO_AUTHORIZE_URL = 'https://autenticacao.neuratechmz.tech/oauth/authorize/'
SSO_TOKEN_URL = 'https://autenticacao.neuratechmz.tech/oauth/token/'
SSO_USERINFO_URL = 'https://autenticacao.neuratechmz.tech/api/auth/user/'
SSO_LOGOUT_URL = 'https://autenticacao.neuratechmz.tech/accounts/logout/'
SSO_REGISTER_URL = 'https://autenticacao.neuratechmz.tech/api/auth/register/'
SSO_LOGIN_URL = 'https://autenticacao.neuratechmz.tech/accounts/login/'
SSO_END_SESSION_ENDPOINT = 'https://autenticacao.neuratechmz.tech/oauth/logout/'

# Outras configurações de segurança
CSRF_TRUSTED_ORIGINS = ['https://admin.paymoz.tech', 'https://paymoz.tech', 'http://127.0.0.1:8000']

# --- Modelo de Usuário Personalizado ---
AUTH_USER_MODEL = 'core.User'

# --- Configurações de E-mail (Gmail) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'neuratech80@gmail.com'
EMAIL_HOST_PASSWORD = 'yfif uazv mniw ksbf'
DEFAULT_FROM_EMAIL = 'neuratech80@gmail.com' # Opcional: define o remetente padrão

# Customização do Admin
ADMIN_SITE_HEADER = "administracao PayMOz"
ADMIN_SITE_TITLE = "administracao PayMOz"
